#!/system/bin/sh
# Device info properties and various device environment variables

# Device Information
export DEVICE_NAME="Retroid Pocket 2+"
export DEVICE_MANUFACTURER="Retroid"
export DEVICE_MODEL="Pocket 2+"
export DEVICE_CODENAME="pocket2plus"

# Device screen configuration
# Screen rotation(in degrees): 0, 90, or 180
export SDL_SCREEN_ROTATION=0
# Skip the SDL encoder ID check
export SDL_SKIP_ENCODER_ID_CHECK=1

# Tell SDL to blacklist unwanted joysticks
export SDL_JOYSTICK_DEVICE_BLACKLIST=touch_joypad:retrogame_joypad

# Override the ALSA default period size
export ALSA_DEFAULT_PERIOD_SIZE=960

# Force ALSA into MMAP mode
export ALSA_FORCE_MMAP=1
